sonar.projectKey=lmilunovic_udas-member-management
sonar.organization=lmilunovic

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# Exclude generated OpenAPI client code
sonar.exclusions=\
  backend/src/main/java/ba/rs/udas/udas_member_management/api/**,\
  backend/src/main/java/ba/rs/udas/udas_member_management/model/**,\
  frontend/src/api/generated/**

sonar.coverage.exclusions=\
  backend/src/main/java/ba/rs/udas/udas_member_management/api/**,\
  backend/src/main/java/ba/rs/udas/udas_member_management/model/**,\
  frontend/src/api/generated/**

sonar.java.source=21
